
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create report directory
      run: if not exist report ( mkdir report )

    - name: Run tests and generate HTML report
      run: pytest  # pytest.ini will handle the report generation

    # Upload the HTML report as an artifact
    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-html-report
        path: report/pytest_html_report.html
